rosbag2_performance_benchmarking:
  benchmark_node:
    ros__parameters:
      benchmark:
        summary_result_file: "70_20_10_results.csv"
        # Bags are written to a ramdisk. `/dev/shm` is available on many unix systems, but feel
        # free to create your own with `sudo mount -t tmpfs foobar <your directory name>`
        db_root_folder: "/dev/shm"
        repeat_each: 5
        no_transport: true
        preserve_bags: false
        parameters:
          max_cache_size:
            - 10240  # 10 KiB
            - 10485760 # 10 MiB
          max_bag_size:           [0]
          compression:            [""]
          compression_queue_size: [1]
          compression_threads:    [0]
          storage:
            - config_file: config/storage/mcap_default.yaml
              id: mcap
            - config_file: config/storage/mcap_nochunking.yaml
              id: mcap
            - config_file: config/storage/mcap_uncompressed_crc.yaml
              id: mcap
            - config_file: config/storage/mcap_compressed_nocrc.yaml
              id: mcap
            - config_file: config/storage/sqlite_default.yaml
              id: sqlite3
            - config_file: config/storage/sqlite_resilient.yaml
              id: sqlite3
