rosbag2_performance_benchmarking:
  benchmark_node:
    ros__parameters:
      benchmark:
        summary_result_file: "results.csv"
        db_root_folder: "shm"
        # How many times to run each configurations (to average results)
        repeat_each: 5
        # Whether to run storage-only or end-to-end (including transport) benchmark
        no_transport: true
        # Whether to leave bag files after experiment (and between runs). Some configurations can take lots of space!
        preserve_bags: false
        # Each combination of parameters in this section will be benchmarked
        parameters:
          max_cache_size:
            - 0
            - 100000
            - 1000000
            - 10000000
            - 100000000
          max_bag_size:           [0]
          compression:            [""]
          compression_queue_size: [1]
          compression_threads:    [0]
          storage:
            - config_file: mcap_default.yaml
              id: mcap
            - config_file: mcap_nochunking.yaml
              id: mcap
            - config_file: mcap_nocrc.yaml
              id: mcap
            - config_file: mcap_uncompressed.yaml
              id: mcap
            - config_file: sqlite_default.yaml
              id: sqlite3
            - config_file: sqlite_resilient.yaml
              id: sqlite3
