rosbag2_performance_benchmarking_node:
  ros__parameters:
    publishers:
      publisher_groups:
        - "100B_messages"
        - "10KiB_messages"
        - "1MiB_messages"
      wait_for_subscriptions: True
      100B_messages:
        # 62MB/s?
        topic_root:         "one_hundred_bytes"
        msg_size_bytes:     100
        publishers_count:   20
        rate_hz:            31457
        msg_count_each:     62914
      10KiB_messages:
        # 125MB/s
        topic_root:         "ten_kibibytes"
        msg_size_bytes:     10240
        publishers_count:   1
        rate_hz:            12288
        msg_count_each:     24576
      1MiB_messages:
        # 440MB/s
        topic_root:         "one_mebibyte"
        msg_size_bytes:     1048576
        publishers_count:   1
        rate_hz:            420
        msg_count_each:     840
